name: Bandit

on:
  push:
    branches: [ "main", "Requirements" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '41 12 * * 1'  # Runs every Monday at 12:41 PM UTC

jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with:
          exit_zero: true  # Exit with 0 even if issues are found
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to get PR information
          # You can uncomment and customize the following options:
          # path: .  # Directory to run Bandit on (default is the root of the repository)
          # level: HIGH  # Only report issues with severity HIGH
          # confidence: HIGH  # Only report issues with confidence HIGH
          # excluded_paths: .git,__pycache__  # Exclude these paths from the scan
          # skips: B101,B102  # Comma-separated list of Bandit test IDs to skip
          # ini_path: .bandit  # Path to a .bandit file that supplies command line arguments
